# Requires the latest version of Docker Compose.
# Docker Compose V2 is recommended.
# `docker-compose.yaml` files cannot use shell outputs as their inputs.
# See https://docs.docker.com/compose/compose-file/compose-file-v3
# for a guide on how to interpret the `docker-compose.yaml` file.
# Variables are in ${VARIBALE:-DEFAULT_VALUE} format
# to ensure that default values are given to the Dockerfile.
# Users are recommended to use an `.env` file to set variables.
# Run `make env` to create a basic `.env` file with the UID and GID variables.

services:
  ngc:
    hostname: ngc
    env_file: 
      - ${ENV_FILE:-.env}
    image: pytorch_source:ngc-${YEAR:-21}.${MONTH:-11}
#    ipc: host
    tty: true
    init: true
    stdin_open: true
    volumes:
      - $PWD:${PROJECT_ROOT:-/opt/project}
    build:
      target: ngc
      context: .
      dockerfile: ngc.Dockerfile
      cache_from: 
        - nvcr.io/nvidia/pytorch:${YEAR:-21}.${MONTH:-11}-py3
      args:
        PROJECT_ROOT: ${PROJECT_ROOT:-/opt/project}
        YEAR: ${YEAR:-21}
        MONTH: ${MONTH:-11}
        GID: ${GID:-1000}
        UID: ${UID:-1000}
        TZ: ${TZ:-Asia/Seoul}
    working_dir: ${PROJECT_ROOT:-/opt/project}
    user: ${UID:-1000}:${GID:-1000}
    environment:
      TZ: ${TZ:-Asia/Seoul}
      CUDA_DEVICE_ORDER: PCI_BUS_ID
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
